
#Sai CLONE--SAITEST Setting #



#spring.datasource.url=jdbc:oracle:thin:@192.168.5.10:1521:SAITEST
#spring.datasource.url=jdbc:oracle:thin:@182.72.0.215:1538:SAIRAJ
#spring.datasource.url=jdbc:oracle:thin:@182.72.0.218:1545:EBSPROD

#spring.datasource.url=jdbc:oracle:thin:@203.115.117.158:1521:SAIERP

#--------------FOR CLONE AS PER ERP NEW CLONE  ----------------
# ----------FOR TESTING LOCALLY --------------
#spring.datasource.url=jdbc:oracle:thin:@172.16.21.220:1535:SAIPROD

#------------FOR GIVING CLONE DEPLOYMENT----------------
#spring.datasource.url=jdbc:oracle:thin:@192.168.5.220:1535:SAIPROD

#------- FOR GIVING CLONE DEPLOYMENT-----------------
#spring.datasource.url=jdbc:oracle:thin:@172.16.21.220:1535:SAIPROD
#spring.datasource.url=jdbc:oracle:thin:@172.16.21.220:1535:SAIPROD



#------for clone new  - OLD SAIRAJ---------
#spring.datasource.url=jdbc:oracle:thin:@192.168.5.17:1538:SAIRAJ

#------for production new ----------

#spring.datasource.url=jdbc:oracle:thin:@192.168.5.140:1545:EBSPROD
spring.datasource.url=jdbc:oracle:thin:@172.16.21.140:1545:EBSPROD



spring.datasource.username=apps 
spring.datasource.password=sainexa20

#Production Server Setting


#spring.datasource.url=jdbc:oracle:thin:@192.168.5.3:1521:SAIOJAS
#spring.datasource.url=jdbc:oracle:thin:@203.115.117.156:1521:SAIOJAS

#Reporting Server Setting
#spring.datasource.url=jdbc:oracle:thin:@192.168.5.3:1521:SAIOJAS
#spring.datasource.url=jdbc:oracle:thin:@203.115.117.156:1521:SAIOJAS
#spring.datasource.username=apps 
#spring.datasource.password=sainexa20

spring.datasource.driver.class=.oracle.jdbc.driver.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
#spring.jpa.properties.hibernate.id.new_generator_mappings = false
spring.jpa.properties.hibernate.format_sql = false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
# for plain hibernate
hibernate.schema_update.unique_constraint_strategy=RECREATE_QUIETLY

# Try increasing the hikari pool size
 spring.datasource.hikari.minimumIdle=10 
 spring.datasource.hikari.maximumPoolSize=200
 spring.datasource.hikari.idleTimeout=120000
 spring.datasource.hikari.maxLifetime=500000

# FOR EMAIL TO USER
spring.mail.host=smtp.saiservice.com
spring.mail.port=587
spring.mail.username=edpborivali@saiservice.com
spring.mail.password=@Sxb42GB!s#4
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.saiservice.com
spring.mail.properties.mail.debug=true


# for spring data
spring.jpa.properties.hibernate.schema_update.unique_constraint_strategy=RECREATE_QUIETLY

spring.datasource.maximumPoolSize=300
spring.datasource.connectionTimeout=1800000

# logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.level.org.hibernate.SQL=DEBUG

server.port=8081
spring.jpa.show-sql=false
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB
spring.servlet.multipart.enabled=true


spring.datasource.tomcat.max-wait=20000
spring.datasource.tomcat.max-active=200
spring.datasource.tomcat.max-idle=20
spring.datasource.tomcat.min-idle=15
spring.datasource.tomcat.initial-size=50 

## Try increasing the hikari pool size
spring.datasource.hikari.minimumIdle=10
spring.datasource.hikari.maximumPoolSize=200
spring.datasource.hikari.idleTimeout=120000
spring.datasource.hikari.maxLifetime=500000
spring.main.lazy-initialization=true


spring.datasource.tomcat.default-auto-commit=true   

#ReportFiles.path=d:\\Reports\\
#ReportFiles.path=//sai_data//Sai_ErpAndroid_Data//
#ReportFiles.path=//sai_data//Sai_ErpAndroid_Data//Vehicle_QR_Store//

#------for clone-----------
#for sales
#ReportFiles.path=/oraarchives/Android_Data_Store/Sai_ErpAndroid_Data/
#for qr generate
#ReportFiles.path=/oraarchives/Android_Data_Store/Vehicle_QR_Store/
#for true value
#ReportFiles.path=/oraarchives/Android_Data_Store/TV_Data_Store/
#for service image
#ReportFiles.path=/oraarchives/Android_Data_Store/Service_Data_Store/
#for workshop 28 image
#ReportFiles.path=/sai14_data/Service_Veh_Data/Veh_Img_Store/


#------for production--------------
#for sales
ReportFiles.path=/sai02_data/Android_Data_Store/Sai_ErpAndroid_Data/
#for qr generate
#ReportFiles.path=/sai02_data/Android_Data_Store/Vehicle_QR_Store/
#for true value
ReportFiles.path=/sai02_data/Android_Data_Store/TV_Data_Store/
#for service image
ReportFiles.path=/sai02_data/Android_Data_Store/Service_Data_Store/
#for workshop 28 image
ReportFiles.path=/sai02_data/Android_Data_Store/Service_Veh_Data/Veh_Img_Store/


#ReportFiles.path=D://wsUpload//

#ReportFiles.path=D://QRUPLOAD//

####/..........image upload path for localhost............
#tv veh image
#ReportFiles.path=D://tvUpload//

#sales veh image
#ReportFiles.path=D://Upload//

#service veh image
#ReportFiles.path=D://srUpload//

##ReportFiles.path=//sai01_data//reports//

##ReportFiles.path=//opt//tomcat9//
##ReportFiles.path=//sai01_data//reports//

#
## for plain hibernate
hibernate.schema_update.unique_constraint_strategy=RECREATE_QUIETLY
#
## for spring data
spring.jpa.properties.hibernate.schema_update.unique_constraint_strategy=RECREATE_QUIETLY



