/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sai.erp.master.controller;

import com.sai.erp.SaiResponse;
import com.sai.erp.master.dao.VehWashingReportDao;
import com.sai.erp.master.dto.VehWashingReportMailDto;
import com.sai.erp.master.service.VehWashReportService;
import java.io.ByteArrayInputStream;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.mail.internet.MimeMessage;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.core.io.InputStreamResource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/**
 *
 * @author HarshG
 */
@RestController
@RequestMapping("/vehWashingReport")
public class VehWashingReportController {

    @Autowired
    private VehWashingReportDao washReportRepo;

    @Autowired
    private VehWashReportService vehWashReportService;

    @Autowired
    private JavaMailSender mailSender;

    //USED FOR REPORT - WASHING REPORT BASED ON OUID
    @GetMapping("/vehWashingReportByOu")
    public SaiResponse washingReportByOu(@RequestParam Integer ouId, @RequestParam Integer locId, @RequestParam Date fromDate, @RequestParam Date toDate)
            throws Exception {
        SaiResponse apiResponse;
        try {

            List<Map> codeList = washReportRepo.getVehWashingReportByOuIdAndLocId(ouId, locId, fromDate, toDate);

            apiResponse = new SaiResponse(200, "Details Found Successfully", codeList);
        } catch (Exception e) {
            apiResponse = new SaiResponse(400, "Details not found", "Details not found");
        }
        return apiResponse;

    }

    //USED FOR WASHING HISTORY OF VEHICLE BASED ON REGNO
    @GetMapping("/vehWashHistoryByRegNo")
    public SaiResponse vehWashHistoryByRegNo(@RequestParam String regNo)
            throws Exception {
        SaiResponse apiResponse;
        try {

            List<Map> codeList = washReportRepo.getVehWashHistoryByRegNo(regNo);

            apiResponse = new SaiResponse(200, "Details Found Successfully", codeList);
        } catch (Exception e) {
            apiResponse = new SaiResponse(400, "Details not found", "Details not found");
        }
        return apiResponse;

    }

    //report to fetch veh wash details as per register
    @GetMapping("/vehWashRegisterReportByOu")
    public SaiResponse vehWashRegisterReportByOu(@RequestParam Integer ouId, @RequestParam Integer locId, @RequestParam Date fromDate, @RequestParam Date toDate)
            throws Exception {
        SaiResponse apiResponse;
        try {

            List<Map> codeList = washReportRepo.getVehWashRegisterReportByOuIdAndLocId(ouId, locId, fromDate, toDate);

            apiResponse = new SaiResponse(200, "Details Found Successfully", codeList);
        } catch (Exception e) {
            apiResponse = new SaiResponse(400, "Details not found", e.getMessage());
        }
        return apiResponse;

    }

    //used to send mail to multiple recipient of the report generated by excel without jasper
    //send mail only excel no jasper
//    @PostMapping("/mailVehWashingReport")
//    public SaiResponse mailVehWashingReport(@RequestBody VehWashingReportMailDto request) throws Exception {
//        SaiResponse apiResponse;
//        try {
//            vehWashReportService.generateAndSendFilteredReport(request);
//
//            apiResponse = new SaiResponse(200, "Report sent successfully", "Report sent successfully to " + request.getEmailList());
//            return apiResponse;
//        } catch (Exception e) {
//
//            apiResponse = new SaiResponse(400, "Failed to send report.", "Failed to send report.");
//            return apiResponse;
//        }
//    }
    //downloading washing report as per jasper design
    //used to download excel report of veh washing , date wise
    @GetMapping("/vehWashingMainReport") // Reporting Server
    public ResponseEntity<InputStreamResource> vehWashingMainReport(@RequestParam Integer ouId, @RequestParam Integer locId, @RequestParam Date fromDate, @RequestParam Date toDate) throws Exception {
        SaiResponse apiResponse = null;
        String status = null;
        String fileName;
        Integer requestId = null;
        try {

            ByteArrayInputStream in;

            Map<String, Object> parameter = new HashMap<>();
            try {

                parameter.put("ouId", ouId);
                parameter.put("locId", locId);
                parameter.put("fromDate", fromDate);
                parameter.put("toDate", toDate);

                fileName = "VehWashingReport.xls";
//                in = vehWashReportService.getVehWashMainReport(parameter, fileName);
                //    status = "Completed";
                //  vehWashReportService.updateReqStat(requestId, status);
                apiResponse = new SaiResponse(200, "Report created normally : ", fileName);

                in = new ByteArrayInputStream(vehWashReportService.getVehWashMainReport(parameter, fileName));

                HttpHeaders headers = new HttpHeaders();
                headers.add("Content-Disposition", "attachment; filename=/download/" + fileName);
                return ResponseEntity
                        .ok()
                        .headers(headers)
                        .body(new InputStreamResource(in));
            } catch (Exception ex) {
                Logger.getLogger(this.getClass()
                        .getName()).log(Level.SEVERE, null, ex);
                ex.printStackTrace();
            }
        } catch (Exception ex) {

            status = "Error";
            throw ex;
        }
        return null;
    }

    //used to mail the veh washing report as per jasper to multiple users
    @PostMapping("/sendVehWashingMainReportMail")
    public ResponseEntity<SaiResponse> sendVehWashingMainReportMail(@RequestBody VehWashingReportMailDto washMail) throws Exception {

        try {
            // Prepare report parameters
            Map<String, Object> parameter = new HashMap<>();
            parameter.put("ouId", washMail.getOuId());
            parameter.put("locId", washMail.getLocId());
            parameter.put("fromDate", washMail.getFromDate());
            parameter.put("toDate", washMail.getToDate());

            String fileName = "VehWashingReport.xls";

            // Generate the report
//            ByteArrayInputStream reportStream = vehWashReportService.getVehWashMainReport(parameter, fileName);
            // Convert InputStream to byte[] for attachment
            byte[] attachmentBytes = vehWashReportService.getVehWashMainReport(parameter, fileName);

            // Send email with attachment
            sendReportByEmail(washMail.getRecipients(), attachmentBytes, fileName);

            SaiResponse apiResponse = new SaiResponse(200, "Report generated and emailed successfully.", fileName);
            return ResponseEntity.ok(apiResponse);

        } catch (Exception e) {
            e.printStackTrace();
            SaiResponse apiResponse = new SaiResponse(500, "Error while sending email: ", null);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(apiResponse);
        }
    }

    private void sendReportByEmail(List<String> recipients, byte[] reportBytes, String fileName) throws MessagingException {

        MimeMessage message = mailSender.createMimeMessage();
        MimeMessageHelper helper = new MimeMessageHelper(message, true);

        String senderEmail = "edpborivali@saiservice.com";

        helper.setFrom(senderEmail);
        helper.setTo(recipients.toArray(new String[0]));
        helper.setSubject("Vehicle Washing Report");
        helper.setText("Please Find Attached Vehicle Washing Report.");

        // Attach the Excel report
        helper.addAttachment(fileName, new ByteArrayResource(reportBytes));

        mailSender.send(message);
    }

    //USED FOR WASHING HISTORY OF VEHICLE BASED ON CHASSIS-NO AND OU 
    @GetMapping("/vehWashHistoryByChassisNo")
    public SaiResponse vehWashHistoryByChassisNo(@RequestParam String chassisNo, @RequestParam Integer ouId)
            throws Exception {
        SaiResponse apiResponse;
        try {

            List<Map> codeList = washReportRepo.getVehWashHistoryByChassisNo(chassisNo, ouId);

            apiResponse = new SaiResponse(200, "Details Found Successfully", codeList);
        } catch (Exception e) {
            apiResponse = new SaiResponse(400, "Details not found", "Details not found");
        }
        return apiResponse;

    }
}
