/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sai.erp.master.dao;

import com.sai.erp.master.entity.SsDmsVehDemo;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.query.Param;

/**
 *
 * @author HarshG
 */
public interface SsDmsVehDemoDao extends CrudRepository<SsDmsVehDemo, Integer> {

    @Query(value = " SELECT NVL(CHASSIS_NO,'-') CHASSIS_NO, NVL(VIN,'-') VIN, NVL(MODEL_DESC,'-') MODEL_DESC, NVL(FUEL_DESC,'-') FUEL_DESC,\n"
            + "NVL(VARIANT_DESC,'-') VARIANT_DESC, NVL(ENGINE_NO,'-') ENGINE_NO\n"
            + "FROM SS_DMS_INV_STOCK WHERE REMARKS LIKE '%Demo Car%' AND VEH_STATUS='STOCK' AND CHASSIS_NO=:chassisNo", nativeQuery = true)
    public List<Map> getDemoVehDetailsByChassisNo(String chassisNo);

    //query for fetching demo veh details by regno in ss_dms_veh_demo table along with last kms
//    @Query(value = " select NVL(cii.instance_number,'-') VEHICLE_NO, NVL(DEMO.CHASSIS_NO,'-') CHASSIS_NO, NVL(DEMO.VIN,'-') VIN, \n"
//            + "NVL(DEMO.MODEL_DESC,'-') MODEL_DESC, NVL(DEMO.FUEL_DESC,'-') FUEL_DESC, NVL(DEMO.VARIANT_DESC,'-') VARIANT_DESC,\n"
//            + "NVL(DEMO.ENGINE_NO,'-') ENGINE_NO, NVL(DEMO.IN_KM,'0') LAST_IN_KM,\n"
//            + "NVL(TO_CHAR(IN_TIME,'DD-MM-YYYY HH24:MI:SS'),'-') IN_TIME,\n"
//            + "NVL(DEMO.FUEL_QTY,'0') FUEL_QTY\n"
//            + "from mtl_system_items_b msi,CSI_ITEM_INSTANCES cii,SS_DMS_INV_STOCK stock, SS_DMS_VEH_DEMO demo\n"
//            + "where msi.attribute6=stock.CHASSIS_NO and msi.attribute12=stock.ENGINE_NO AND msi.ORGANIZATION_ID=119\n"
//            + "AND DEMO.CHASSIS_NO=STOCK.CHASSIS_NO AND DEMO.VIN=STOCK.VIN\n"
//            + "and msi.INVENTORY_ITEM_ID=cii.INVENTORY_ITEM_ID and cii.instance_number=:regNo AND STOCK.REMARKS LIKE '%Demo Car%'\n"
//            + "AND STOCK.VEH_STATUS='STOCK' ORDER BY UPDATION_DATE DESC \n"
//            + "fetch first 1 rows only", nativeQuery = true)
//    public List<Map> getDemoVehDetailsPresentByRegNo(String regNo);
    //query updated as per last km from stk trsfer table 
//    @Query(value = "  WITH veh_stock AS (\n"
//            + "                SELECT DEMO.CHASSIS_NO, DEMO.VIN, DEMO.ENGINE_NO, DEMO.MODEL_DESC, DEMO.FUEL_DESC,\n"
//            + "                       DEMO.VARIANT_DESC, DEMO.FUEL_QTY_IN, DEMO.IN_KM, DEMO.IN_TIME,\n"
//            + "                       CII.INSTANCE_NUMBER, stock.VARIANT_CODE , stock.COLOUR, stock.COLOUR_CODE\n"
//            + "                FROM MTL_SYSTEM_ITEMS_B MSI, CSI_ITEM_INSTANCES CII, SS_DMS_INV_STOCK STOCK, SS_DMS_VEH_DEMO DEMO\n"
//            + "                WHERE MSI.ATTRIBUTE6 = STOCK.CHASSIS_NO\n"
//            + "                  AND MSI.ATTRIBUTE12 = STOCK.ENGINE_NO\n"
//            + "                  AND MSI.ORGANIZATION_ID = 119\n"
//            + "                  AND DEMO.CHASSIS_NO = STOCK.CHASSIS_NO\n"
//            + "                  AND DEMO.VIN = STOCK.VIN\n"
//            + "                  AND MSI.INVENTORY_ITEM_ID = CII.INVENTORY_ITEM_ID\n"
//            + "                  AND CII.INSTANCE_NUMBER = :regNo\n"
//            + "                  AND STOCK.REMARKS LIKE '%Demo Car%'\n"
//            + "                  AND STOCK.VEH_STATUS = 'STOCK'\n"
//            + "                  and stock.location= :location \n"
//            + "                ORDER BY DEMO.UPDATION_DATE DESC\n"
//            + "                FETCH FIRST 1 ROWS ONLY\n"
//            + "            ),\n"
//            + "            km_events AS (\n"
//            + "                SELECT VS.CHASSIS_NO, VS.VIN, VS.ENGINE_NO,\n"
//            + "                       VS.IN_KM        AS EVENT_KM,\n"
//            + "                       VS.IN_TIME      AS EVENT_DATE,\n"
//            + "                       'DEMO'          AS SRC\n"
//            + "                FROM veh_stock VS\n"
//            + "                UNION ALL\n"
//            + "                SELECT TRF.CHASSIS_NO, TRF.VIN, TRF.ENGINE_NO,\n"
//            + "                       TO_NUMBER(TRF.TOKM)  AS EVENT_KM,\n"
//            + "                       TRF.RECD_DATE         AS EVENT_DATE,\n"
//            + "                       'TRF'                 AS SRC\n"
//            + "                FROM SS_DMS_STOCK_TRF TRF, veh_stock VS\n"
//            + "                WHERE TRF.CHASSIS_NO = VS.CHASSIS_NO\n"
//            + "                  AND TRF.VIN        = VS.VIN\n"
//            + "                  AND TRF.ENGINE_NO  = VS.ENGINE_NO\n"
//            + "                  AND TRF.RECD_DATE IS NOT NULL\n"
//            + "            ),\n"
//            + "            latest_event AS (\n"
//            + "                SELECT * FROM km_events\n"
//            + "                ORDER BY EVENT_DATE DESC\n"
//            + "                FETCH FIRST 1 ROWS ONLY\n"
//            + "            )\n"
//            + "            SELECT NVL(VS.INSTANCE_NUMBER,'-')                              VEHICLE_NO,\n"
//            + "                   NVL(VS.CHASSIS_NO,'-')                                   CHASSIS_NO,\n"
//            + "                   NVL(VS.VIN,'-')                                          VIN,\n"
//            + "                   NVL(VS.MODEL_DESC,'-')                                   MODEL_DESC,\n"
//            + "                   NVL(VS.FUEL_DESC,'-')                                    FUEL_DESC,\n"
//            + "                   NVL(VS.VARIANT_DESC,'-')                                 VARIANT_DESC,\n"
//            + "                   NVL(VS.ENGINE_NO,'-')                                    ENGINE_NO,\n"
//            + "                   NVL(TO_CHAR(LE.EVENT_KM),'0')                             LAST_IN_KM,\n"
//            + "                   NVL(TO_CHAR(LE.EVENT_DATE,'DD-MM-YYYY HH24:MI:SS'),'-')   IN_TIME,\n"
//            + "                   NVL(TO_CHAR(VS.FUEL_QTY_IN),'0')                             FUEL_QTY,\n"
//            + "                   NVL(VS.VARIANT_CODE,'-')                                 VARIANT_CODE,\n"
//            + "                   NVL(VS.COLOUR,'-')                                 COLOUR,\n"
//            + "                   NVL(VS.COLOUR_CODE,'-')                                 COLOUR_CODE\n"
//            + "            FROM veh_stock VS, latest_event LE", nativeQuery = true)
//    public List<Map> getDemoVehDetailsPresentByRegNo(String regNo, String location);
    //updated as per nexa arena bifur and last kms
    @Query(value
            = "WITH veh_stock AS ( \n"
            + "    SELECT CII.INSTANCE_NUMBER, \n"
            + "           STOCK.CHASSIS_NO, \n"
            + "           STOCK.VIN, \n"
            + "           STOCK.MODEL_DESC, \n"
            + "           STOCK.FUEL_DESC, \n"
            + "           STOCK.VARIANT_DESC, \n"
            + "           STOCK.ENGINE_NO, \n"
            + "           STOCK.VARIANT_CODE, \n"
            + "           STOCK.COLOUR, \n"
            + "           STOCK.COLOUR_CODE \n"
            + "    FROM MTL_SYSTEM_ITEMS_B MSI \n"
            + "    JOIN CSI_ITEM_INSTANCES CII \n"
            + "      ON MSI.INVENTORY_ITEM_ID = CII.INVENTORY_ITEM_ID \n"
            + "    JOIN SS_DMS_INV_STOCK STOCK \n"
            + "      ON MSI.ATTRIBUTE6 = STOCK.CHASSIS_NO \n"
            + "     AND MSI.ATTRIBUTE12 = STOCK.ENGINE_NO \n"
            + "    LEFT JOIN FND_COMMON_LOOKUPS FCL \n"
            + "      ON FCL.LOOKUP_CODE = STOCK.VARIANT_CODE \n"
            + "     AND FCL.LOOKUP_TYPE = 'SS_MSIL_SALES_CODE' \n"
            + "    WHERE MSI.ORGANIZATION_ID = 119 \n"
            + "      AND CII.INSTANCE_NUMBER = :regNo \n"
            + "      AND STOCK.REMARKS LIKE '%Demo Car%' \n"
            + "      AND STOCK.VEH_STATUS = 'STOCK' \n"
            + "      AND STOCK.LOCATION = :location \n"
            // Arena / Nexa restriction
            + "      AND FCL.LOOKUP_CODE IS NOT NULL \n"
            + "      AND ( \n"
            + "             ( :salesType = 'NEXA' \n"
            + "               AND UPPER(NVL(FCL.DESCRIPTION, '')) LIKE '%NEXA%' ) \n"
            + "          OR ( :salesType = 'ARENA' \n"
            + "               AND UPPER(NVL(FCL.DESCRIPTION, '')) NOT LIKE '%NEXA%' ) \n"
            + "          ) \n"
            + "), \n"
            + "km_events AS ( \n"
            + "    SELECT DEMO.CHASSIS_NO, \n"
            + "           DEMO.VIN, \n"
            + "           DEMO.ENGINE_NO, \n"
            + "           DEMO.IN_KM AS EVENT_KM, \n"
            + "           DEMO.IN_TIME AS EVENT_DATE, \n"
            + "           'DEMO' AS SRC \n"
            + "    FROM SS_DMS_VEH_DEMO DEMO, veh_stock VS \n"
            + "    WHERE DEMO.CHASSIS_NO = VS.CHASSIS_NO \n"
            + "      AND DEMO.VIN = VS.VIN \n"
            + "    UNION ALL \n"
            + "    SELECT TRF.CHASSIS_NO, \n"
            + "           TRF.VIN, \n"
            + "           TRF.ENGINE_NO, \n"
            + "           TO_NUMBER(TRF.TOKM) AS EVENT_KM, \n"
            + "           TRF.RECD_DATE AS EVENT_DATE, \n"
            + "           'TRF' AS SRC \n"
            + "    FROM SS_DMS_STOCK_TRF TRF, veh_stock VS \n"
            + "    WHERE TRF.CHASSIS_NO = VS.CHASSIS_NO \n"
            + "      AND TRF.VIN = VS.VIN \n"
            + "      AND TRF.ENGINE_NO = VS.ENGINE_NO \n"
            + "      AND TRF.RECD_DATE IS NOT NULL \n"
            + "), \n"
            + "latest_event AS ( \n"
            + "    SELECT * \n"
            + "    FROM km_events \n"
            + "    ORDER BY EVENT_DATE DESC \n"
            + "    FETCH FIRST 1 ROWS ONLY \n"
            + ") \n"
            + "SELECT NVL(VS.INSTANCE_NUMBER, '-') VEHICLE_NO, \n"
            + "       NVL(VS.CHASSIS_NO, '-') CHASSIS_NO, \n"
            + "       NVL(VS.VIN, '-') VIN, \n"
            + "       NVL(VS.MODEL_DESC, '-') MODEL_DESC, \n"
            + "       NVL(VS.FUEL_DESC, '-') FUEL_DESC, \n"
            + "       NVL(VS.VARIANT_DESC, '-') VARIANT_DESC, \n"
            + "       NVL(VS.ENGINE_NO, '-') ENGINE_NO, \n"
            + "       NVL(VS.VARIANT_CODE, '-') VARIANT_CODE, \n"
            + "       NVL(VS.COLOUR, '-') COLOUR, \n"
            + "       NVL(VS.COLOUR_CODE, '-') COLOUR_CODE, \n"
            + "       NVL(TO_CHAR(LE.EVENT_KM), '0') LAST_IN_KM, \n"
            + "       NVL(TO_CHAR(LE.EVENT_DATE, 'DD-MM-YYYY HH24:MI:SS'), '-') IN_TIME \n"
            + "FROM veh_stock VS \n"
            + "LEFT JOIN latest_event LE ON 1 = 1",
            nativeQuery = true)
    public List<Map> getDemoVehDetailsPresentByRegNo(
            @Param("regNo") String regNo,
            @Param("location") String location,
            @Param("salesType") String salesType);

    //query for fetching demo veh details by regno in stock table 
//    @Query(value = " select NVL(cii.instance_number,'-') VEHICLE_NO, NVL(STOCK.CHASSIS_NO,'-') CHASSIS_NO, NVL(STOCK.VIN,'-') VIN, \n"
//            + "NVL(STOCK.MODEL_DESC,'-') MODEL_DESC, NVL(STOCK.FUEL_DESC,'-') FUEL_DESC, NVL(STOCK.VARIANT_DESC,'-') VARIANT_DESC,\n"
//            + "NVL(STOCK.ENGINE_NO,'-') ENGINE_NO\n"
//            + " from mtl_system_items_b msi,CSI_ITEM_INSTANCES cii,SS_DMS_INV_STOCK stock\n"
//            + " where msi.attribute6=stock.CHASSIS_NO and msi.attribute12=stock.ENGINE_NO AND msi.ORGANIZATION_ID=119\n"
//            + "and msi.INVENTORY_ITEM_ID=cii.INVENTORY_ITEM_ID and cii.instance_number=:regNo AND STOCK.REMARKS LIKE '%Demo Car%'\n"
//            + "AND STOCK.VEH_STATUS='STOCK'", nativeQuery = true)
//    public List<Map> getDemoVehDetailsByRegNo(String regNo);
    //updated query along with location 
//    @Query(value = " select NVL(cii.instance_number,'-') VEHICLE_NO, NVL(STOCK.CHASSIS_NO,'-') CHASSIS_NO, NVL(STOCK.VIN,'-') VIN, \n"
//            + " NVL(STOCK.MODEL_DESC,'-') MODEL_DESC, NVL(STOCK.FUEL_DESC,'-') FUEL_DESC, NVL(STOCK.VARIANT_DESC,'-') VARIANT_DESC,\n"
//            + "  NVL(STOCK.ENGINE_NO,'-') ENGINE_NO , NVL(STOCK.VARIANT_CODE,'-') VARIANT_CODE, NVL(STOCK.COLOUR,'-') COLOUR,\n"
//            + "  NVL(STOCK.COLOUR_CODE,'-') COLOUR_CODE \n"
//            + "  from mtl_system_items_b msi,CSI_ITEM_INSTANCES cii,SS_DMS_INV_STOCK stock\n"
//            + " where msi.attribute6=stock.CHASSIS_NO and msi.attribute12=stock.ENGINE_NO AND msi.ORGANIZATION_ID=119\n"
//            + " and msi.INVENTORY_ITEM_ID=cii.INVENTORY_ITEM_ID and cii.instance_number=:regNo AND STOCK.REMARKS LIKE '%Demo Car%'\n"
//            + " AND STOCK.VEH_STATUS='STOCK' and stock.location=:location ", nativeQuery = true)
//    public List<Map> getDemoVehDetailsByRegNo(String regNo, String location);
    //updated query along with location and last kms
//    @Query(value = " WITH veh_stock AS (\n"
//            + "    SELECT CII.INSTANCE_NUMBER, STOCK.CHASSIS_NO, STOCK.VIN, STOCK.MODEL_DESC, STOCK.FUEL_DESC,\n"
//            + "           STOCK.VARIANT_DESC, STOCK.ENGINE_NO, STOCK.VARIANT_CODE, STOCK.COLOUR, STOCK.COLOUR_CODE\n"
//            + "    FROM MTL_SYSTEM_ITEMS_B MSI, CSI_ITEM_INSTANCES CII, SS_DMS_INV_STOCK STOCK\n"
//            + "    WHERE MSI.ATTRIBUTE6 = STOCK.CHASSIS_NO\n"
//            + "      AND MSI.ATTRIBUTE12 = STOCK.ENGINE_NO\n"
//            + "      AND MSI.ORGANIZATION_ID = 119\n"
//            + "      AND MSI.INVENTORY_ITEM_ID = CII.INVENTORY_ITEM_ID\n"
//            + "      AND CII.INSTANCE_NUMBER = :regNo\n"
//            + "      AND STOCK.REMARKS LIKE '%Demo Car%'\n"
//            + "      AND STOCK.VEH_STATUS = 'STOCK'\n"
//            + "      AND STOCK.LOCATION = :location\n"
//            + "),\n"
//            + "km_events AS (\n"
//            + "    SELECT DEMO.CHASSIS_NO, DEMO.VIN, DEMO.ENGINE_NO,\n"
//            + "           DEMO.IN_KM   AS EVENT_KM,\n"
//            + "           DEMO.IN_TIME AS EVENT_DATE,\n"
//            + "           'DEMO'       AS SRC\n"
//            + "    FROM SS_DMS_VEH_DEMO DEMO, veh_stock VS\n"
//            + "    WHERE DEMO.CHASSIS_NO = VS.CHASSIS_NO\n"
//            + "      AND DEMO.VIN        = VS.VIN\n"
//            + "    UNION ALL\n"
//            + "    SELECT TRF.CHASSIS_NO, TRF.VIN, TRF.ENGINE_NO,\n"
//            + "           TO_NUMBER(TRF.TOKM) AS EVENT_KM,\n"
//            + "           TRF.RECD_DATE       AS EVENT_DATE,\n"
//            + "           'TRF'               AS SRC\n"
//            + "    FROM SS_DMS_STOCK_TRF TRF, veh_stock VS\n"
//            + "    WHERE TRF.CHASSIS_NO = VS.CHASSIS_NO\n"
//            + "      AND TRF.VIN        = VS.VIN\n"
//            + "      AND TRF.ENGINE_NO  = VS.ENGINE_NO\n"
//            + "      AND TRF.RECD_DATE IS NOT NULL\n"
//            + "),\n"
//            + "latest_event AS (\n"
//            + "    SELECT * FROM km_events\n"
//            + "    ORDER BY EVENT_DATE DESC\n"
//            + "    FETCH FIRST 1 ROWS ONLY\n"
//            + ")\n"
//            + "SELECT NVL(VS.INSTANCE_NUMBER,'-')                              VEHICLE_NO,\n"
//            + "       NVL(VS.CHASSIS_NO,'-')                                   CHASSIS_NO,\n"
//            + "       NVL(VS.VIN,'-')                                          VIN,\n"
//            + "       NVL(VS.MODEL_DESC,'-')                                   MODEL_DESC,\n"
//            + "       NVL(VS.FUEL_DESC,'-')                                    FUEL_DESC,\n"
//            + "       NVL(VS.VARIANT_DESC,'-')                                 VARIANT_DESC,\n"
//            + "       NVL(VS.ENGINE_NO,'-')                                    ENGINE_NO,\n"
//            + "       NVL(VS.VARIANT_CODE,'-')                                 VARIANT_CODE,\n"
//            + "       NVL(VS.COLOUR,'-')                                       COLOUR,\n"
//            + "       NVL(VS.COLOUR_CODE,'-')                                  COLOUR_CODE,\n"
//            + "       NVL(TO_CHAR(LE.EVENT_KM),'0')                             LAST_IN_KM,\n"
//            + "       NVL(TO_CHAR(LE.EVENT_DATE,'DD-MM-YYYY HH24:MI:SS'),'-')   IN_TIME\n"
//            + "FROM veh_stock VS\n"
//            + "LEFT JOIN latest_event LE ON 1=1 ", nativeQuery = true)
//    public List<Map> getDemoVehDetailsByRegNo(String regNo, String location);
    //updated as per sales type - arena/ nexa and location 
    @Query(value
            = "WITH veh_stock AS ( \n"
            + "    SELECT CII.INSTANCE_NUMBER, \n"
            + "           STOCK.CHASSIS_NO, \n"
            + "           STOCK.VIN, \n"
            + "           STOCK.MODEL_DESC, \n"
            + "           STOCK.FUEL_DESC, \n"
            + "           STOCK.VARIANT_DESC, \n"
            + "           STOCK.ENGINE_NO, \n"
            + "           STOCK.VARIANT_CODE, \n"
            + "           STOCK.COLOUR, \n"
            + "           STOCK.COLOUR_CODE \n"
            + "    FROM MTL_SYSTEM_ITEMS_B MSI \n"
            + "    JOIN CSI_ITEM_INSTANCES CII \n"
            + "      ON MSI.INVENTORY_ITEM_ID = CII.INVENTORY_ITEM_ID \n"
            + "    JOIN SS_DMS_INV_STOCK STOCK \n"
            + "      ON MSI.ATTRIBUTE6 = STOCK.CHASSIS_NO \n"
            + "     AND MSI.ATTRIBUTE12 = STOCK.ENGINE_NO \n"
            + "    LEFT JOIN FND_COMMON_LOOKUPS FCL \n"
            + "      ON FCL.LOOKUP_CODE = STOCK.VARIANT_CODE \n"
            + "     AND FCL.LOOKUP_TYPE = 'SS_MSIL_SALES_CODE' \n"
            + "    WHERE MSI.ORGANIZATION_ID = 119 \n"
            + "      AND CII.INSTANCE_NUMBER = :regNo \n"
            + "      AND STOCK.REMARKS LIKE '%Demo Car%' \n"
            + "      AND STOCK.VEH_STATUS = 'STOCK' \n"
            + "      AND STOCK.LOCATION = :location \n"
            // Arena / Nexa restriction
            + "      AND FCL.LOOKUP_CODE IS NOT NULL \n"
            + "      AND ( \n"
            + "             ( :salesType = 'NEXA' \n"
            + "               AND UPPER(NVL(FCL.DESCRIPTION, '')) LIKE '%NEXA%' ) \n"
            + "          OR ( :salesType = 'ARENA' \n"
            + "               AND UPPER(NVL(FCL.DESCRIPTION, '')) NOT LIKE '%NEXA%' ) \n"
            + "          ) \n"
            + "), \n"
            + "km_events AS ( \n"
            + "    SELECT DEMO.CHASSIS_NO, \n"
            + "           DEMO.VIN, \n"
            + "           DEMO.ENGINE_NO, \n"
            + "           DEMO.IN_KM AS EVENT_KM, \n"
            + "           DEMO.IN_TIME AS EVENT_DATE, \n"
            + "           'DEMO' AS SRC \n"
            + "    FROM SS_DMS_VEH_DEMO DEMO, veh_stock VS \n"
            + "    WHERE DEMO.CHASSIS_NO = VS.CHASSIS_NO \n"
            + "      AND DEMO.VIN = VS.VIN \n"
            + "    UNION ALL \n"
            + "    SELECT TRF.CHASSIS_NO, \n"
            + "           TRF.VIN, \n"
            + "           TRF.ENGINE_NO, \n"
            + "           TO_NUMBER(TRF.TOKM) AS EVENT_KM, \n"
            + "           TRF.RECD_DATE AS EVENT_DATE, \n"
            + "           'TRF' AS SRC \n"
            + "    FROM SS_DMS_STOCK_TRF TRF, veh_stock VS \n"
            + "    WHERE TRF.CHASSIS_NO = VS.CHASSIS_NO \n"
            + "      AND TRF.VIN = VS.VIN \n"
            + "      AND TRF.ENGINE_NO = VS.ENGINE_NO \n"
            + "      AND TRF.RECD_DATE IS NOT NULL \n"
            + "), \n"
            + "latest_event AS ( \n"
            + "    SELECT * \n"
            + "    FROM km_events \n"
            + "    ORDER BY EVENT_DATE DESC \n"
            + "    FETCH FIRST 1 ROWS ONLY \n"
            + ") \n"
            + "SELECT NVL(VS.INSTANCE_NUMBER, '-') VEHICLE_NO, \n"
            + "       NVL(VS.CHASSIS_NO, '-') CHASSIS_NO, \n"
            + "       NVL(VS.VIN, '-') VIN, \n"
            + "       NVL(VS.MODEL_DESC, '-') MODEL_DESC, \n"
            + "       NVL(VS.FUEL_DESC, '-') FUEL_DESC, \n"
            + "       NVL(VS.VARIANT_DESC, '-') VARIANT_DESC, \n"
            + "       NVL(VS.ENGINE_NO, '-') ENGINE_NO, \n"
            + "       NVL(VS.VARIANT_CODE, '-') VARIANT_CODE, \n"
            + "       NVL(VS.COLOUR, '-') COLOUR, \n"
            + "       NVL(VS.COLOUR_CODE, '-') COLOUR_CODE, \n"
            + "       NVL(TO_CHAR(LE.EVENT_KM), '0') LAST_IN_KM, \n"
            + "       NVL(TO_CHAR(LE.EVENT_DATE, 'DD-MM-YYYY HH24:MI:SS'), '-') IN_TIME \n"
            + "FROM veh_stock VS \n"
            + "LEFT JOIN latest_event LE ON 1 = 1",
            nativeQuery = true)
    public List<Map> getDemoVehDetailsByRegNo(
            @Param("regNo") String regNo,
            @Param("location") String location,
            @Param("salesType") String salesType);

//    @Query(value = " SELECT nvl(REG_NO,'-') REG_NO, NVL(CHASSIS_NO,'-') CHASSIS_NO, NVL(VIN,'-') VIN, NVL(MODEL_DESC,'-') MODEL_DESC, NVL(FUEL_DESC,'-') FUEL_DESC,\n"
//            + "NVL(VARIANT_DESC,'-') VARIANT_DESC, NVL(ENGINE_NO,'-') ENGINE_NO, NVL(LOC_ID,0) LOC_ID , NVL(OU_ID,0) OU_ID,\n"
//            + "NVL(LOCATION,'-') LOCATION, NVL(CUST_NAME,'-') CUST_NAME, NVL(CUST_CONTACT_NO,'-') CUST_CONTACT_NO, NVL(CUST_ADDRESS,'-') CUST_ADDRESS,\n"
//            + "NVL(REMARKS,'-') REMARKS, NVL(OUT_KM,0) OUT_KM, NVL(TO_CHAR(OUT_TIME,'DD-MM-YYYY HH24:MI:SS'),'-') OUT_TIME,\n"
//            + "NVL(FUEL_QTY,'0') FUEL_QTY,\n"
//            + "NVL(CREATED_BY,'-') CREATED_BY, NVL(TO_CHAR(CREATION_DATE,'DD-MM-YYYY HH24:MI:SS'),'-') CREATION_DATE,\n"
//            + "NVL(UPDATED_BY,'-') UPDATED_BY , NVL(TO_CHAR(UPDATION_DATE,'DD-MM-YYYY HH24:MI:SS'),'-') UPDATION_DATE,\n"
//            + "NVL(ATTRIBUTE1,'-') GATE_NO, NVL(ATTRIBUTE2,'-') GATE_TYPE\n"
//            + "FROM SS_DMS_VEH_DEMO WHERE REG_NO=:regNo AND OUT_KM IS NOT NULL and IN_KM IS NULL ORDER BY CREATION_DATE DESC\n"
//            + "fetch first 1 rows only", nativeQuery = true)
//    public List<Map> getDemoVehInDetailsByRegNo(String regNo);
//    @Query(value = "  SELECT  NVL(demo.REG_NO, '-') REG_NO, NVL(demo.CHASSIS_NO, '-') CHASSIS_NO, NVL(demo.VIN, '-') VIN,\n"
//            + "NVL(demo.MODEL_DESC, '-') MODEL_DESC, NVL(demo.FUEL_DESC, '-') FUEL_DESC, NVL(demo.VARIANT_DESC, '-') VARIANT_DESC,\n"
//            + "NVL(demo.ENGINE_NO, '-') ENGINE_NO, NVL(demo.LOC_ID, 0) LOC_ID, NVL(demo.OU_ID, 0) OU_ID,\n"
//            + "NVL(demo.LOCATION, '-') LOCATION, NVL(demo.CUST_NAME, '-') CUST_NAME,\n"
//            + "NVL(demo.CUST_CONTACT_NO, '-') CUST_CONTACT_NO, NVL(demo.CUST_ADDRESS, '-') CUST_ADDRESS,\n"
//            + "NVL(demo.REMARKS, '-') REMARKS, NVL(demo.OUT_KM, 0) OUT_KM, NVL(TO_CHAR(demo.OUT_TIME, 'DD-MM-YYYY HH24:MI:SS'), '-') OUT_TIME,\n"
//            + "NVL(demo.FUEL_QTY, '0') FUEL_QTY, NVL(demo.CREATED_BY, '-') CREATED_BY,\n"
//            + "NVL(TO_CHAR(demo.CREATION_DATE, 'DD-MM-YYYY HH24:MI:SS'), '-') CREATION_DATE,\n"
//            + "NVL(demo.UPDATED_BY, '-') UPDATED_BY, NVL(TO_CHAR(demo.UPDATION_DATE, 'DD-MM-YYYY HH24:MI:SS'), '-') UPDATION_DATE,\n"
//            + "NVL(demo.ATTRIBUTE1, '-') GATE_NO, NVL(demo.ATTRIBUTE2, '-') GATE_TYPE,\n"
//            + "NVL(stock.VARIANT_CODE, '-') VARIANT_CODE, NVL(stock.COLOUR, '-') COLOUR, NVL(stock.COLOUR_CODE, '-') COLOUR_CODE\n"
//            + "FROM SS_DMS_VEH_DEMO demo, SS_DMS_INV_STOCK stock \n"
//            + "WHERE STOCK.VEH_STATUS='STOCK'   AND STOCK.REMARKS LIKE '%Demo Car%'\n"
//            + "and stock.chassis_no=demo.CHASSIS_NO and stock.engine_no= demo.ENGINE_NO and\n"
//            + "demo.REG_NO = :regNo  AND stock.LOCATION = :location\n"
//            + "AND demo.OUT_KM IS NOT NULL AND demo.IN_KM IS NULL\n"
//            + "ORDER BY demo.CREATION_DATE DESC\n"
//            + "FETCH FIRST 1 ROWS ONLY", nativeQuery = true)
//    public List<Map> getDemoVehInDetailsByRegNo(String regNo, String location);
//updated as per nexa arena bifur
    @Query(value
            = "SELECT NVL(demo.REG_NO, '-') REG_NO, "
            + "       NVL(demo.CHASSIS_NO, '-') CHASSIS_NO, "
            + "       NVL(demo.VIN, '-') VIN, "
            + "       NVL(demo.MODEL_DESC, '-') MODEL_DESC, "
            + "       NVL(demo.FUEL_DESC, '-') FUEL_DESC, "
            + "       NVL(demo.VARIANT_DESC, '-') VARIANT_DESC, "
            + "       NVL(demo.ENGINE_NO, '-') ENGINE_NO, "
            + "       NVL(demo.LOC_ID, 0) LOC_ID, "
            + "       NVL(demo.OU_ID, 0) OU_ID, "
            + "       NVL(demo.LOCATION, '-') LOCATION, "
            + "       NVL(demo.CUST_NAME, '-') CUST_NAME, "
            + "       NVL(demo.CUST_CONTACT_NO, '-') CUST_CONTACT_NO, "
            + "       NVL(demo.CUST_ADDRESS, '-') CUST_ADDRESS, "
            + "       NVL(demo.REMARKS, '-') REMARKS, "
            + "       NVL(demo.OUT_KM, 0) OUT_KM, "
            + "       NVL(TO_CHAR(demo.OUT_TIME, 'DD-MM-YYYY HH24:MI:SS'), '-') OUT_TIME, "
            + "       NVL(demo.FUEL_QTY, '0') FUEL_QTY, "
            + "       NVL(demo.CREATED_BY, '-') CREATED_BY, "
            + "       NVL(TO_CHAR(demo.CREATION_DATE, 'DD-MM-YYYY HH24:MI:SS'), '-') CREATION_DATE, "
            + "       NVL(demo.UPDATED_BY, '-') UPDATED_BY, "
            + "       NVL(TO_CHAR(demo.UPDATION_DATE, 'DD-MM-YYYY HH24:MI:SS'), '-') UPDATION_DATE, "
            + "       NVL(demo.ATTRIBUTE1, '-') GATE_NO, "
            + "       NVL(demo.ATTRIBUTE2, '-') GATE_TYPE, "
            + "       NVL(stock.VARIANT_CODE, '-') VARIANT_CODE, "
            + "       NVL(stock.COLOUR, '-') COLOUR, "
            + "       NVL(stock.COLOUR_CODE, '-') COLOUR_CODE "
            + "FROM SS_DMS_VEH_DEMO demo "
            + "JOIN SS_DMS_INV_STOCK stock "
            + "  ON stock.CHASSIS_NO = demo.CHASSIS_NO "
            + " AND stock.ENGINE_NO = demo.ENGINE_NO "
            + "LEFT JOIN FND_COMMON_LOOKUPS FCL "
            + "  ON FCL.LOOKUP_CODE = stock.VARIANT_CODE "
            + " AND FCL.LOOKUP_TYPE = 'SS_MSIL_SALES_CODE' "
            + "WHERE stock.VEH_STATUS = 'STOCK' "
            + "  AND stock.REMARKS LIKE '%Demo Car%' "
            + "  AND demo.REG_NO = :regNo "
            + "  AND stock.LOCATION = :location "
            + "  AND demo.OUT_KM IS NOT NULL "
            + "  AND demo.IN_KM IS NULL "
            + "  AND FCL.LOOKUP_CODE IS NOT NULL "
            + "  AND ( "
            + "         ( :salesType = 'NEXA' "
            + "           AND UPPER(NVL(FCL.DESCRIPTION, '')) LIKE '%NEXA%' ) "
            + "      OR ( :salesType = 'ARENA' "
            + "           AND UPPER(NVL(FCL.DESCRIPTION, '')) NOT LIKE '%NEXA%' ) "
            + "      ) "
            + "ORDER BY demo.CREATION_DATE DESC "
            + "FETCH FIRST 1 ROWS ONLY",
            nativeQuery = true)
    public List<Map> getDemoVehInDetailsByRegNo(
            @Param("regNo") String regNo,
            @Param("location") String location,
            @Param("salesType") String salesType);

    public Optional<SsDmsVehDemo> findFirstByChassisNoOrderByCreationDateDesc(String chassisNo);

//    public Optional<SsDmsVehDemo> findFirstByRegNoOrderByCreationDateDesc(String regNo);
    //query for demo sales report by location and date wise
    @Query(value = " select ROW_NUMBER() OVER (ORDER BY CREATION_DATE DESC) AS sr_no, NVL(REG_NO,'-') REG_NO, NVL(chassis_no,'-') CHASSIS_NO, NVL(MODEL_DESC,'-') MODEL_DESC, NVL(FUEL_DESC,'-') FUEL_DESC,\n"
            + " NVL(VARIANT_DESC,'-') VARIANT_DESC, NVL(ENGINE_NO,'-') ENGINE_NO, NVL(CUST_NAME,'-') CUST_NAME, NVL(CUST_ADDRESS,'-') CUST_ADDRESS,\n"
            + "NVL(CUST_CONTACT_NO,'-') CUST_CONTACT_NO, NVL(REMARKS,'-') REMARKS,\n"
            + "NVL(IN_REMARKS,'-') IN_REMARKS,\n"
            + "NVL(LOC_ID,0) LOC_ID, NVL(OU_ID,0) OU_ID,NVL(LOCATION,'-') LOCATION, NVL(ATTRIBUTE1,'-') ATTRIBUTE1, NVL(ATTRIBUTE2,'-') ATTRIBUTE2,\n"
            + " NVL(OUT_KM,0) OUT_KM, NVL(TO_CHAR(OUT_TIME,'DD-MM-YYYY HH24:MI:SS'),'-') OUT_TIME, \n"
            + " NVL(IN_KM,0) IN_KM, NVL(TO_CHAR(IN_TIME,'DD-MM-YYYY HH24:MI:SS'),'-') IN_TIME,\n"
            + "NVL(FUEL_QTY,0) FUEL_QTY, NVL(FUEL_QTY_IN,0) FUEL_QTY_IN , NVL(ATTRIBUTE3,'-') ATTRIBUTE3, NVL(GATE_PASS_NO,0) GATE_PASS_NO,\n"
            + "NVL(CREATED_BY,'-') CREATED_BY, NVL(TO_CHAR(CREATION_DATE,'YYYY-MM-DD HH24:MI:SS'),'-') CREATION_DATE,\n"
            + "NVL(UPDATED_BY,'-') UPDATED_BY, NVL(SOB_ENQ_DET,'-') SOB_ENQ_DET, NVL(TO_CHAR(UPDATION_DATE,'DD-MM-YYYY HH24:MI:SS'),'-') UPDATION_DATE\n"
            + "FROM SS_DMS_VEH_DEMO WHERE OU_ID=:ouId and LOC_ID=:locId  and CREATION_DATE BETWEEN :fromDate AND :toDate \n"
            + "ORDER BY CREATION_DATE desc", nativeQuery = true)
    public List<Map> getDemoVehReportByOuIdAndLocId(Integer ouId, Integer locId, Date fromDate, Date toDate);

//    @Query(value = "SELECT DISTINCT LOC_ID , LOCATION FROM SS_DMS_VEH_DEMO where OU_ID=?1 ORDER BY LOC_ID", nativeQuery = true)
//    public List<Map> getLocationDetailsByOu(Integer ouId);
    @Query(value = " SELECT DISTINCT stk.location, usr.locid as loc_id \n"
            + "FROM ss_dms_inv_stock stk\n"
            + "INNER JOIN ss_veh_stock_login usr\n"
            + "    ON usr.location_name = stk.location\n"
            + "WHERE stk.remarks = 'Demo Car'\n"
            + "  AND stk.veh_status = 'STOCK'\n"
            + "  AND stk.operating_unit = ?1  and usr.deptname='SALES DEMO'\n"
            + "  ORDER BY STK.LOCATION", nativeQuery = true)
    public List<Map> getLocationDetailsByOu(Integer ouId);

    //query for demo sales report by location and date wise
//    @Query(value = " SELECT \n"
//            + "     cii.instance_number,\n"
//            + "    CASE\n"
//            + "        WHEN (\n"
//            + "            SELECT COUNT(*) \n"
//            + "            FROM ss_dms_veh_demo d\n"
//            + "            WHERE d.vin = stk.vin \n"
//            + "              AND d.out_time IS NOT NULL \n"
//            + "              AND d.in_time IS NULL\n"
//            + "        ) > 0 THEN 'OUT FOR DEMO'\n"
//            + "        ELSE 'AVAILABLE'\n"
//            + "    END AS STATUS\n"
//            + "FROM \n"
//            + "    ss_dms_inv_stock stk, csi_item_instances cii, mtl_system_items_b msi\n"
//            + "     where stk.remarks like '%Demo Car%'\n"
//            + "   and msi.attribute6=stk.CHASSIS_NO and msi.attribute12=stk.ENGINE_NO AND msi.ORGANIZATION_ID=119\n"
//            + "   and  msi.INVENTORY_ITEM_ID=cii.INVENTORY_ITEM_ID\n"
//            + "    and stk.VEH_status='STOCK' and STK.OPERATING_UNIT=?1 and stk.location=?2", nativeQuery = true)
//    public List<Map> getDemoVehStatusListByOu(Integer ouId, String location);
//    @Query(value = "SELECT \n"
//            + "    cii.instance_number,\n"
//            + "    CASE\n"
//            + "        WHEN d.vin IS NOT NULL THEN 'OUT FOR DEMO'\n"
//            + "        ELSE 'AVAILABLE'\n"
//            + "    END AS status,\n"
//            + "    d.out_time,\n"
//            + "    d.created_by,\n"
//            + "    d.attribute3,\n"
//            + "    d.cust_name,\n"
//            + "    d.cust_address\n"
//            + "FROM ss_dms_inv_stock stk\n"
//            + "JOIN mtl_system_items_b msi \n"
//            + "    ON msi.attribute6 = stk.CHASSIS_NO \n"
//            + "   AND msi.attribute12 = stk.ENGINE_NO \n"
//            + "   AND msi.ORGANIZATION_ID = 119\n"
//            + "JOIN csi_item_instances cii \n"
//            + "    ON msi.INVENTORY_ITEM_ID = cii.INVENTORY_ITEM_ID\n"
//            + "LEFT JOIN ss_dms_veh_demo d\n"
//            + "    ON d.vin = stk.vin\n"
//            + "   AND d.out_time IS NOT NULL\n"
//            + "   AND d.in_time IS NULL\n"
//            + "WHERE stk.remarks LIKE '%Demo Car%'\n"
//            + "  AND stk.VEH_status = 'STOCK'\n"
//            + "  AND stk.OPERATING_UNIT = ?1\n"
//            + "  AND stk.location = ?2", nativeQuery = true)
//    public List<Map> getDemoVehStatusListByOu(Integer ouId, String location);
//    @Query(value = " SELECT  cii.instance_number,\n"
//            + "    CASE\n"
//            + "    WHEN d.vin IS NOT NULL AND d.in_time IS NULL THEN 'OUT FOR DEMO'\n"
//            + "     ELSE 'AVAILABLE'\n"
//            + "    END AS status,\n"
//            + "    CASE WHEN d.in_time IS NULL THEN d.out_time END AS out_time,\n"
//            + "     CASE WHEN d.in_time IS NULL THEN d.created_by END AS created_by,\n"
//            + "     CASE WHEN d.in_time IS NULL THEN d.attribute3 END AS attribute3,\n"
//            + "    CASE WHEN d.in_time IS NULL THEN d.cust_name END AS cust_name,\n"
//            + "    CASE WHEN d.in_time IS NULL THEN d.cust_address END AS cust_address,\n"
//            + "    COALESCE(d.model_desc, stk.model_desc) AS model_desc,\n"
//            + "     nvl(stk.variant_code,'-') as variant_code,\n"
//            + "     nvl(stk.colour,'-') as colour,\n"
//            + "     nvl(stk.colour_code,'-') as colour_code\n"
//            + "    FROM ss_dms_inv_stock stk\n"
//            + "    JOIN mtl_system_items_b msi \n"
//            + "    ON msi.attribute6 = stk.CHASSIS_NO \n"
//            + "    AND msi.attribute12 = stk.ENGINE_NO \n"
//            + "    AND msi.ORGANIZATION_ID = 119\n"
//            + "    JOIN csi_item_instances cii \n"
//            + "    ON msi.INVENTORY_ITEM_ID = cii.INVENTORY_ITEM_ID\n"
//            + "    LEFT JOIN (\n"
//            + "     SELECT \n"
//            + "     vin,\n"
//            + "     out_time,\n"
//            + "     in_time,       \n"
//            + "    created_by,\n"
//            + "     attribute3,\n"
//            + "    cust_name,\n"
//            + "    cust_address,\n"
//            + "    model_desc,\n"
//            + "     ROW_NUMBER() OVER (\n"
//            + "    PARTITION BY vin \n"
//            + "     ORDER BY id DESC \n"
//            + "     ) AS rn\n"
//            + "    FROM ss_dms_veh_demo\n"
//            + "     WHERE out_time IS NOT NULL \n"
//            + "     ) d\n"
//            + "      ON d.vin = stk.vin\n"
//            + "     AND d.rn = 1           \n"
//            + "  WHERE stk.remarks LIKE '%Demo Car%'\n"
//            + " AND stk.VEH_status = 'STOCK'\n"
//            + " AND stk.OPERATING_UNIT = :ouId \n"
//            + " AND stk.location = :location \n"
//            + "order by status desc", nativeQuery = true)
//    public List<Map> getDemoVehStatusListByOu(Integer ouId, String location);
    //updated as per nexa arena bifur
    @Query(value
            = " SELECT cii.instance_number, \n"
            + "    CASE \n"
            + "        WHEN d.vin IS NOT NULL AND d.in_time IS NULL \n"
            + "        THEN 'OUT FOR DEMO' \n"
            + "        ELSE 'AVAILABLE' \n"
            + "    END AS status, \n"
            + "    CASE WHEN d.in_time IS NULL THEN d.out_time END AS out_time, \n"
            + "    CASE WHEN d.in_time IS NULL THEN d.created_by END AS created_by, \n"
            + "    CASE WHEN d.in_time IS NULL THEN d.attribute3 END AS attribute3, \n"
            + "    CASE WHEN d.in_time IS NULL THEN d.cust_name END AS cust_name, \n"
            + "    CASE WHEN d.in_time IS NULL THEN d.cust_address END AS cust_address, \n"
            + "    COALESCE(d.model_desc, stk.model_desc) AS model_desc, \n"
            + "    NVL(stk.variant_code, '-') AS variant_code, \n"
            + "    NVL(stk.colour, '-') AS colour, \n"
            + "    NVL(stk.colour_code, '-') AS colour_code \n"
            + " FROM ss_dms_inv_stock stk \n"
            + " JOIN mtl_system_items_b msi \n"
            + "   ON msi.attribute6 = stk.chassis_no \n"
            + "  AND msi.attribute12 = stk.engine_no \n"
            + "  AND msi.organization_id = 119 \n"
            + " JOIN csi_item_instances cii \n"
            + "   ON msi.inventory_item_id = cii.inventory_item_id \n"
            + " LEFT JOIN fnd_common_lookups fcl \n"
            + "   ON fcl.lookup_code = stk.variant_code \n"
            + "  AND fcl.lookup_type = 'SS_MSIL_SALES_CODE' \n"
            + " LEFT JOIN ( \n"
            + "     SELECT vin, \n"
            + "            out_time, \n"
            + "            in_time, \n"
            + "            created_by, \n"
            + "            attribute3, \n"
            + "            cust_name, \n"
            + "            cust_address, \n"
            + "            model_desc, \n"
            + "            ROW_NUMBER() OVER ( \n"
            + "                PARTITION BY vin \n"
            + "                ORDER BY id DESC \n"
            + "            ) AS rn \n"
            + "     FROM ss_dms_veh_demo \n"
            + "     WHERE out_time IS NOT NULL \n"
            + " ) d \n"
            + "   ON d.vin = stk.vin \n"
            + "  AND d.rn = 1 \n"
            + " WHERE stk.remarks LIKE '%Demo Car%' \n"
            + "   AND stk.veh_status = 'STOCK' \n"
            + "   AND stk.operating_unit = :ouId \n"
            + "   AND stk.location = :location \n"
            + "   AND fcl.lookup_code IS NOT NULL \n"
            + "   AND ( \n"
            + "          ( :salesType = 'NEXA' \n"
            + "            AND UPPER(NVL(fcl.description, '')) LIKE '%NEXA%' ) \n"
            + "       OR ( :salesType = 'ARENA' \n"
            + "            AND UPPER(NVL(fcl.description, '')) NOT LIKE '%NEXA%' ) \n"
            + "       ) \n"
            + " ORDER BY status DESC",
            nativeQuery = true)
    public List<Map> getDemoVehStatusListByOu(
            @Param("ouId") Integer ouId,
            @Param("location") String location,
            @Param("salesType") String salesType);

    public Optional<SsDmsVehDemo> findFirstByRegNoAndLocationOrderByCreationDateDesc(String regNo, String location);

    @Query(value = "SELECT STOCK.LOCATION_NAME "
            + "FROM MTL_SYSTEM_ITEMS_B MSI "
            + "JOIN CSI_ITEM_INSTANCES CII "
            + "  ON MSI.INVENTORY_ITEM_ID = CII.INVENTORY_ITEM_ID "
            + "JOIN SS_DMS_INV_STOCK STOCK "
            + "  ON MSI.ATTRIBUTE6 = STOCK.CHASSIS_NO "
            + " AND MSI.ATTRIBUTE12 = STOCK.ENGINE_NO "
            + "WHERE MSI.ORGANIZATION_ID = 119 "
            + "  AND CII.INSTANCE_NUMBER = :regNo",
            nativeQuery = true)
    List<String> getLocationNameByRegNo(@Param("regNo") String regNo);
}
